### ISSUE TITLE
A few errors via ESLint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-mailer#22]
### Steps to reproduce:

1. `$ npm i eslint`
2. Create an .eslintrc file with the following sauce:

    ```yaml
env:
      node: true

rules:
      comma-spacing: 0
      quotes: [0, single]
      semi: false
      space-unary-ops: 0
      strict: 0
```
3. `$ eslint .`

### Actual results:

```
$ eslint .

bin/server.js
  45:72  error  'body' is not defined                             no-undef
  71:4   error  Don't use process.exit(); throw an error instead  no-process-exit

test/mail_helper.js
  24:4   error  mail is defined but never used               no-unused-vars
  38:16  error  mail is already declared in the upper scope  no-shadow
  39:12  error  uid is defined but never used                no-unused-vars
  71:6   error  mail is already declared in the upper scope  no-shadow

✖ 6 problems
```

### Expected results:

Probably nothing matters. I'm guessing that the [/bin/server.js:45](https://github.com/mozilla/fxa-auth-mailer/blob/f90dfa3f2a893fdc8e6ece24858840a67f2732c3/bin/server.js#L45) should be `req.body` instead of just `body`:
```js
log.error({
  op: 'send',
  err: {
    message: 'invalid type',
    body: body
  }
})
```
